version: '3.7'

services:
  jupyter:
    build: ./
    container_name: jupyter-notebook
    image: jupyter-with-rise:latest
    ports:
      - "8888:8888"
    volumes:
      # /home/jovyan/work is the default directory that comes with the jupyter image
      - "./Interactive\ Slides/:/home/jovyan/work"
    restart: unless-stopped
